In [48]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head()


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

1

In [6]:
pd.__version__

'2.3.2'

2

In [12]:
df.shape

# there are 9704 records

(9704, 11)

3

In [13]:
df['fuel_type'].value_counts()

# there are 2 types.

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

4

In [18]:
df.isnull().sum()

# there are 4 columns with null values

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

5

In [25]:
Asia_cars = df[df['origin'] == 'Asia']
max_mpg = Asia_cars['fuel_efficiency_mpg'].max()
print(f"the max fuel efficiency of Asia cars is: {max_mpg:.2f} mpg")

the max fuel efficiency of Asia cars is: 23.76 mpg


6

In [26]:
df['horsepower'].median()

np.float64(149.0)

In [32]:
freq = df['horsepower'].mode()[0]
freq

np.float64(152.0)

In [33]:
df['horsepower'].isnull().sum()

np.int64(708)

In [34]:
df['horsepower'].fillna(freq, inplace=True)

C:\Users\rohit\AppData\Local\Temp\ipykernel_3624\1395087079.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(freq, inplace=True)


In [37]:
df['horsepower'].isnull().sum()

np.int64(0)

In [35]:
df['horsepower'].median()

np.float64(152.0)

the meadian value increased

7

In [42]:
Asia_cars = df[df['origin'] == 'Asia']
Asia_cars = df[['vehicle_weight', 'model_year']]

In [43]:
Asia_cars.head()

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009

In [85]:
asia_cars = Asia_cars.head(7)

In [86]:
x = np.array(asia_cars)

In [96]:
x

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [97]:
U = x.T

In [98]:
XTX = U.dot(x)

In [99]:
XTX

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [100]:
XTX_inv = np.linalg.inv(XTX)

In [101]:
XTX_inv

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [102]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [103]:
w = XTX_inv.dot(U).dot(y)


In [104]:
w

array([0.07099685, 0.41931263])

In [106]:
print(w.sum())

0.4903094879707426
